-- ============================================================
-- CaszaMosqui — Datos de ejemplo (seed)
-- FormosaHack 2026 · El Colorado, Formosa
-- Barrios reales según plano oficial (coordenadas X% Y%)
-- ============================================================
USE formosahack;

-- Tipos de criadero (clasificación oficial dengue)
INSERT INTO tipos_criadero (nombre, color, icono) VALUES
  ('Recipientes con agua',    '#dc2626', '🪣'),
  ('Neumáticos',              '#d97706', '🛞'),
  ('Piletas y tanques',       '#2563eb', '🛁'),
  ('Zanjas y agua estancada', '#0891b2', '💧'),
  ('Basurales y residuos',    '#16a34a', '🗑️'),
  ('Botellas y cacharros',    '#9333ea', '🍾');

-- Barrios de El Colorado (coordenadas del plano oficial)
INSERT INTO barrios (nombre, localidad, x, y, poblacion) VALUES
  ('Barrio Mosconi',            'El Colorado', 22,  9,  1200),
  ('Barrio Eva Perón',          'El Colorado', 41, 10,  1500),
  ('Barrio Los Halcones',       'El Colorado', 56, 10,  1100),
  ('Barrio Mitre',              'El Colorado', 15, 20,  950),
  ('Barrio San Pantaleón',      'El Colorado', 34, 18,  1300),
  ('Barrio San Juan Norte',     'El Colorado', 44, 22,  1400),
  ('Barrio Diego F. Sevilla',   'El Colorado', 62, 24,  1000),
  ('Barrio La Paz',             'El Colorado', 94, 20,  800),
  ('Barrio 2 de Abril',         'El Colorado', 12, 30,  1150),
  ('Barrio San Martín',         'El Colorado', 37, 31,  1600),
  ('Barrio Independiente',      'El Colorado', 63, 33,  1200),
  ('Barrio La Pileta',          'El Colorado', 24, 39,  900),
  ('Barrio San Miguel',         'El Colorado', 52, 45,  1350),
  ('Barrio I.P.V.',             'El Colorado', 66, 45,  1450),
  ('Barrio Terminal de Ómnibus', 'El Colorado', 81, 37,  1100),
  ('Barrio Aeropuerto',         'El Colorado', 84, 48,  700),
  ('Barrio La Peña',            'El Colorado', 33, 51,  850),
  ('Barrio I.N.T.A.',           'El Colorado', 42, 51,  900),
  ('Barrio M. M. Güemes',       'El Colorado', 57, 58,  1050),
  ('Barrio 82 Viviendas',       'El Colorado', 66, 58,  1250),
  ('Barrio Vicentín',           'El Colorado', 27, 58,  750),
  ('Barrio Pellegrini',         'El Colorado', 38, 65,  950),
  ('Barrio El Surco',           'El Colorado', 61, 77,  800),
  ('Barrio Vialidad',           'El Colorado', 82, 65,  850);

-- Reportes de criaderos (distribuidos por barrios, variedad de estados y tipos)
INSERT INTO reportes (tipo_id, barrio_id, titulo, descripcion, referencia, estado, votos) VALUES
  (1, 10, 'Baldes y tachos en obra abandonada',
   'Recipientes sin tapa acumulando agua de lluvia en galpón en construcción.',
   'Calle San Martín 300', 'pendiente', 14),
  (1, 4, 'Tachos sin tapa en casa en obra',
   'Varios recipientes descubiertos en patio en obra, agua estancada desde días.',
   'Av. 25 de Mayo y Rivadavia', 'pendiente', 9),
  (2, 13, 'Neumáticos apilados en taller',
   'Más de 20 cubiertas usadas con agua estancada detrás del taller mecánico.',
   'Ruta 81 km 1164', 'pendiente', 22),
  (2, 14, 'Gomería acumula cubiertas al aire libre',
   'Neumáticos apilados sin cobertura, con agua de las últimas lluvias.',
   'Bv. San Martín y Sarmiento', 'verificado', 11),
  (3, 5, 'Pileta sin tratamiento en club',
   'Pileta del club con agua estancada verde, sin mantenimiento hace semanas.',
   'Club Sportivo, 25 de Mayo', 'pendiente', 18),
  (3, 13, 'Tanque descubierto en vivienda',
   'Tanque de agua sin tapa en vivienda familiar, acceso directo de mosquitos.',
   'Barrio San Miguel, manzana 4', 'verificado', 7),
  (4, 12, 'Zanja obstruida con agua estancada',
   'Desagüe tapado genera charco permanente en la esquina.',
   'Barrio La Pileta, calle 8 y 9', 'pendiente', 31),
  (4, 3, 'Charco en terreno descampado',
   'Agua acumulada en bajo nivel detrás de la plaza, no evacúa.',
   'Barrio Los Halcones, frente a plaza', 'pendiente', 12),
  (5, 15, 'Acumulación de residuos en zona terminal',
   'Puntos de basura sin recolección cerca de terminal, atraen mosquitos y roedores.',
   'Terminal de Ómnibus, sector sur', 'pendiente', 27),
  (5, 9, 'Basural improvisado en predio',
   'Desechos acumulados detrás del supermercado, agua en envases y bolsas.',
   'Barrio 2 de Abril, manzana 12', 'controlado', 8),
  (1, 22, 'Macetas y platitos con agua en veredas',
   'Platitos de macetas en comercios de la esquina acumulan agua.',
   'Barrio Pellegrini, esquina céntrica', 'pendiente', 5),
  (6, 1, 'Botellas y latas en terreno baldío',
   'Gran cantidad de botellas y latas con agua en lote sin cerrar.',
   'Barrio Mosconi, lote 7', 'verificado', 6),
  (6, 5, 'Cacharros en patio vecinal',
   'Electrodomésticos en desuso y objetos de plástico acumulando agua.',
   'Barrio San Pantaleón, manzana 2', 'controlado', 3),
  (4, 10, 'Zanja a cielo abierto frente a escuela',
   'Zanja sin entubar frente a escuela primaria, agua estancada permanente.',
   'Barrio San Martín, calle Reconquista', 'pendiente', 40),
  (1, 2, 'Recipientes en vivienda deshabitada',
   'Casa abandonada con tinas y baldes juntando agua de lluvia.',
   'Barrio Eva Perón, manzana 1', 'pendiente', 6),
  (2, 8, 'Neumáticos en desarmadero',
   'Desarmadero con cubiertas expuestas a la intemperie.',
   'Barrio La Paz, acceso norte', 'verificado', 4),
  (3, 11, 'Pileta familiar sin cloro',
   'Pileta de lona sin tratamiento en patio trasero.',
   'Barrio Independiente, manzana 3', 'pendiente', 9),
  (5, 7, 'Residuos en microbasural',
   'Acumulación de bolsas y envases en esquina sin recolección.',
   'Barrio San Juan Norte, esquina', 'pendiente', 15),
  (1, 17, 'Floreros y bebederos sin limpiar',
   'Bebederos de animales y floreros con agua estancada.',
   'Barrio La Peña, zona rural', 'verificado', 2),
  (6, 21, 'Latas y botellas en predio escolar',
   'Patio de escuela con envases acumulando agua.',
   'Barrio 82 Viviendas, escuela N° 42', 'pendiente', 10);